"""Passive trace recorder for equivariant data produced during forward passes.

This module records semantic equivariant values emitted by `EquivariantMap`
instances (and manual trace points) during a normal model forward pass. It is
deliberately *passive*: it never permutes, compares, validates, or fails.
Future runtime equivariance checkers consume the recorded traces; this module
only captures them.

Tracing is controlled by a context-local active trace
(:class:`contextvars.ContextVar`). When no trace is active,
:func:`trace_equivariant` is a no-op.
"""

from __future__ import annotations

import warnings
from contextlib import contextmanager
from contextvars import ContextVar
from dataclasses import dataclass
from typing import Any, Iterator


class EquivarianceTraceWarning(UserWarning):
    """Warning for imperfect trace naming (fallback names, duplicate keys)."""


@dataclass
class EquivarianceTraceEntry:
    """One recorded equivariant value.

    Parameters
    ----------
    index : int
        Monotonically increasing recording index within the active trace,
        starting from zero.
    key : str
        Resolved entry key (e.g. ``"layers.0.update/output"``). Disambiguated
        with a ``#<n>`` suffix on collision.
    value : Any
        The recorded value. Any value may be recorded; no protocol is required.
    slot : str
        Semantic slot the value was recorded under (e.g. ``"output"``).
    producer_name : str or None, optional
        Resolved base name of the producer (trace_name, module path, or
        fallback). ``None`` when only an explicit key was supplied.
    producer_type : str or None, optional
        Class name of the producer, when a producer was supplied.
    fallback_name : bool, optional
        Whether the producer name was generated by fallback naming.
    """

    index: int
    key: str
    value: Any
    slot: str
    producer_name: str | None = None
    producer_type: str | None = None
    fallback_name: bool = False


_active_trace: ContextVar["EquivarianceTrace | None"] = ContextVar(
    "spenn_equivariance_active_trace", default=None
)


class EquivarianceTrace:
    """Context-local recorder of equivariant values during a forward pass.

    Usage::

        with EquivarianceTrace.capture(model=model) as trace:
            output = model(batch)

    When created with a ``model``, the trace builds an ``id(module) ->
    module_path`` map from ``model.named_modules()`` so that producers record
    themselves under stable PyTorch module paths without any module mutation.

    Parameters
    ----------
    model : torch.nn.Module or None, optional
        Model whose ``named_modules()`` provide producer name resolution.
    """

    def __init__(self, model: Any = None) -> None:
        self._entries: list[EquivarianceTraceEntry] = []
        self._by_key: dict[str, EquivarianceTraceEntry] = {}
        self._module_paths: dict[int, str] = {}
        # Fallback bookkeeping: next index per class name, and a stable assigned
        # base name per producer id so repeated slots reuse one fallback name.
        self._fallback_class_counts: dict[str, int] = {}
        self._fallback_assigned: dict[int, str] = {}
        self._warned_fallback: set[int] = set()
        if model is not None:
            for name, module in model.named_modules():
                if name:  # skip the root module, whose named_modules name is ""
                    self._module_paths[id(module)] = name

    @classmethod
    @contextmanager
    def capture(cls, model: Any = None) -> Iterator["EquivarianceTrace"]:
        """Activate a fresh trace for the duration of the context.

        Parameters
        ----------
        model : torch.nn.Module or None, optional
            Model used to resolve producer names from module paths.

        Yields
        ------
        EquivarianceTrace
            The active trace, into which forward passes record entries.
        """

        trace = cls(model=model)
        token = _active_trace.set(trace)
        try:
            yield trace
        finally:
            _active_trace.reset(token)

    @property
    def entries(self) -> tuple[EquivarianceTraceEntry, ...]:
        """Return recorded entries in insertion order."""

        return tuple(self._entries)

    def keys(self) -> tuple[str, ...]:
        """Return recorded keys in insertion order."""

        return tuple(entry.key for entry in self._entries)

    def __len__(self) -> int:
        """Return the number of recorded entries."""

        return len(self._entries)

    def __iter__(self) -> Iterator[EquivarianceTraceEntry]:
        """Iterate over recorded entries in insertion order."""

        return iter(self._entries)

    def __contains__(self, key: str) -> bool:
        """Return whether `key` was recorded."""

        return key in self._by_key

    def __getitem__(self, key: str) -> EquivarianceTraceEntry:
        """Return the entry recorded under `key`."""

        return self._by_key[key]

    def get(self, key: str, default: Any = None) -> Any:
        """Return the entry recorded under `key`, or `default`."""

        return self._by_key.get(key, default)

    def record(
        self,
        value: Any,
        *,
        slot: str = "output",
        producer: object | None = None,
        key: str | None = None,
    ) -> EquivarianceTraceEntry:
        """Record one value, resolving its key by name priority.

        Name priority: explicit `key`, then ``producer.trace_name``, then the
        producer's PyTorch module path, then a generated ``<ClassName><index>``
        fallback. Duplicate keys are kept and disambiguated with a ``#<n>``
        suffix. Both fallback naming and duplicate keys warn (but never fail).
        """

        producer_type = None if producer is None else type(producer).__name__
        if key is not None:
            entry_key = key
            producer_name = self._resolve_base_name(producer, warn=False)[0]
            fallback = False
        else:
            producer_name, fallback = self._resolve_base_name(producer, warn=True)
            base = producer_name if producer_name is not None else slot
            entry_key = base if producer_name is None else f"{producer_name}/{slot}"

        entry_key = self._disambiguate(entry_key)
        entry = EquivarianceTraceEntry(
            index=len(self._entries),
            key=entry_key,
            value=value,
            slot=slot,
            producer_name=producer_name,
            producer_type=producer_type,
            fallback_name=fallback,
        )
        self._entries.append(entry)
        self._by_key[entry_key] = entry
        return entry

    def _resolve_base_name(self, producer: object | None, *, warn: bool) -> tuple[str | None, bool]:
        """Resolve a producer's base name (trace_name, module path, or fallback)."""

        if producer is None:
            return None, False
        trace_name = getattr(producer, "trace_name", None)
        if trace_name:
            return str(trace_name), False
        path = self._module_paths.get(id(producer))
        if path:
            return path, False
        return self._assign_fallback(producer, warn=warn), True

    def _assign_fallback(self, producer: object, *, warn: bool) -> str:
        """Assign (and cache) a stable ``<ClassName><index>`` fallback name."""

        producer_id = id(producer)
        assigned = self._fallback_assigned.get(producer_id)
        if assigned is None:
            class_name = type(producer).__name__
            index = self._fallback_class_counts.get(class_name, 0)
            self._fallback_class_counts[class_name] = index + 1
            assigned = f"{class_name}{index}"
            self._fallback_assigned[producer_id] = assigned
        if warn and producer_id not in self._warned_fallback:
            self._warned_fallback.add(producer_id)
            warnings.warn(
                f"EquivarianceTrace: producer {type(producer).__name__} has no "
                f"trace_name or module path; using fallback name {assigned}.",
                EquivarianceTraceWarning,
                stacklevel=4,
            )
        return assigned

    def _disambiguate(self, entry_key: str) -> str:
        """Return a unique key, suffixing ``#<n>`` and warning on collision."""

        if entry_key not in self._by_key:
            return entry_key
        suffix = 1
        while f"{entry_key}#{suffix}" in self._by_key:
            suffix += 1
        disambiguated = f"{entry_key}#{suffix}"
        warnings.warn(
            f"EquivarianceTrace: duplicate trace key {entry_key!r}; "
            f"recording as {disambiguated!r}.",
            EquivarianceTraceWarning,
            stacklevel=4,
        )
        return disambiguated


def trace_equivariant(
    value: Any,
    *,
    slot: str = "output",
    producer: object | None = None,
    key: str | None = None,
) -> None:
    """Record `value` to the active trace, or do nothing if none is active.

    Parameters
    ----------
    value : Any
        Equivariant value to record.
    slot : str, optional
        Semantic slot (e.g. ``"output"``, ``"interaction"``).
    producer : object or None, optional
        Producing module, used for name resolution.
    key : str or None, optional
        Explicit full key that overrides all other name resolution.
    """

    trace = _active_trace.get()
    if trace is None:
        return
    trace.record(value, slot=slot, producer=producer, key=key)


__all__ = [
    "EquivarianceTrace",
    "EquivarianceTraceEntry",
    "EquivarianceTraceWarning",
    "trace_equivariant",
]
