seed: 1234
dtype: float64
device: cuda

system:
  _target_: spenn.physics.systems.ElectronicSystem
  name: toy
  n_electrons: 2
  spatial_dim: 3
  harmonic_omega: 1.0
  dtype: ${dtype}

model:
  _target_: spenn.nn.wavefunction.SpENNWavefunction
  encoder:
    _target_: spenn.nn.encoding.electron_features.ElectronPairEncoder
    name: basic
    max_order: 2
    channels:
      order1:
        "(1)": 32
      order2:
        "(2)": 32
        "(1,1)": 32
    include_spins: true
  spechtmp:
    _target_: spenn.nn.spechtmp.layer.SpechtMP
    M: 2
    M_virtual: 2
    num_layers: 4
    residual: true
    activation:
      _target_: spenn.nn.activations.TensorProductActivation
    normalization: null
  readout:
    _target_: spenn.nn.readout.pfaffian.PfaffianReadout
    name: pfaffian
    num_pfaffians: 1
    use_symmetric_gates: true
    allow_odd_electron_bordered: true
  cusp:
    _target_: spenn.nn.encoding.cusp.ElectronElectronCusp
    enabled: false

hamiltonian:
  _target_: spenn.physics.hamiltonian.ElectronicHamiltonian
  name: electronic
  kinetic:
    _target_: spenn.physics.kinetic.LogAbsKineticEnergy
  potential:
    _target_: spenn.physics.potential.ElectronicPotential
    eps: 1.0e-12

sampler:
  _target_: spenn.sampling.metropolis.MetropolisSampler
  name: metropolis
  move:
    _target_: spenn.sampling.moves.GaussianMove
    step_size: 0.05
    move_all: true
  n_walkers: 1024
  warmup_steps: 100
  steps_per_iter: 10
  initial_scale: 1.0

loss:
  _target_: spenn.losses.vmc.VMCLoss

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001

trainer:
  _target_: spenn.training.trainer.VMCTrainer
  max_steps: 1000
  log_every: 10
  checkpoint_every: 100
