# TODO: Implement only order-1 and order-2 features for the first M=2 prototype.
_target_: spenn.nn.encoding.electron_features.ElectronPairEncoder
name: basic
max_order: 2
channels:
  order1:
    "(1)": 32
  order2:
    "(2)": 32
    "(1,1)": 32
include_spins: true
implementation_status: pending
